market_site/home/__init__.py
from flask import Blueprint, render_template
from flask_login import login_required
from flask_breadcrumbs import default_breadcrumb_root, register_breadcrumb

home = Blueprint("home", __name__, url_prefix="/home", template_folder="templates")


# from .asset_routes import *
# from .auction_routes import *
# from .sale_routes import *
# from .loan_routes import *
# from .transacion_routes import *

default_breadcrumb_root(home, '.')


from market_site.home import asset_routes
from market_site.home import auction_routes
from market_site.home import sale_routes
from market_site.home import loan_routes
from market_site.home import transacion_routes

@home.route('/')
@login_required
@register_breadcrumb(home, '.', 'Home')
def user_home():
	return render_template('home/home.html', title='Home')

market_site/market/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from market_site import bc, db
from market_site.models import *
from market_site.config import *
from flask_login import current_user, login_required

# /user_assets is in the "routest.py" file
market = Blueprint("market", __name__, url_prefix="/market", template_folder="templates")

@market.route('/')
@login_required
def market_():
	return render_template('market/market.html', title='Market')


@market.route('/auctions')
@login_required
def auctions():
	page = request.args.get('page', 1, type=int)
	auctions = db.session.query(Auction)\
		.where(Auction.status == FOR_SALE, Auction.seller_id != current_user.id)\
		.paginate(page=page, per_page=12)
	return render_template('market/auctions.html', title='Auctions', auctions=auctions)


@market.route('/assets/h')
@login_required
def market_hard_assets():
	return render_template('market/ha_market_overview.html', title='Hard asset')

@market.route('/assets/h/<string:category>')
@login_required
def market_hard_asset_category(category):
	page = request.args.get('page', 1, type=int)
	category = category.upper()
	ha_type = category
	# sales = HardAssetSale.query.filter_by(status=FOR_SALE, hard_asset.type=type).all()
	sales = db.session.query(HardAssetSale)\
		.join(HardAsset, HardAssetSale.hard_asset_id==HardAsset.id)\
		.where(HardAssetSale.status == FOR_SALE, HardAsset.type == ha_type)\
		.paginate(page=page, per_page=12)
	title = ha_type.lower().replace('_', ' ').capitalize()
	return render_template('market/ha_market.html', title=title, sales=sales, category=category.lower())








@market.route('/assets/l')
@login_required
def market_liquid_assets():
	return render_template('market/la_market_overview.html', title='Liquid asset')



@market.route('/assets/l/bonds')
@login_required
def market_bonds():
	companies = Company.query.all()
	return render_template('market/bond_market.html', title='Bond market', companies=companies)



@market.route('/assets/l/stocks')
@login_required
def market_stocks():
	companies = Company.query.all()
	return render_template('market/stock_market.html', title='Stock market', companies=companies)



@market.route('/assets/l/stocks/<int:company_id>/sell', methods = ['GET', 'POST'])
@login_required
def market_sell_stock(company_id):
	company = Company.query.get_or_404(company_id)
	user_share_number = current_user.share_number(company)
	if request.method == 'POST':
		share_number = request.form.get('share_number')
		price = request.form.get('price')
		try:
			share_number = float(share_number)
			price = float(price)
			if share_number <= user_share_number and price >= 0:

				for i, s in enumerate(current_user.get_shares(company)):
					if i < share_number:
						ss = CompanyShareSale(
							price = price,
							status = FOR_SALE,
							share_id = s.id,
							seller_id = current_user.id,
						)
						db.session.add(ss)
						db.session.commit()
		except ValueError:
			flash('value error', 'error')
	return render_template('market/company_stock_sell.html', title='Company stock market', company=company, user_share_number=current_user.share_number(company))



@market.route('/assets/l/bonds/<int:company_id>/sell', methods = ['GET', 'POST'])
@login_required
def market_sell_bond(company_id):
	company = Company.query.get_or_404(company_id)
	user_bond_number = current_user.bond_number(company)
	if request.method == 'POST':
		bond_number = request.form.get('bond_number')
		price = request.form.get('price')
		try:
			bond_number = float(bond_number)
			price = float(price)
			if bond_number <= user_bond_number and price >= 0:

				for i, s in enumerate(current_user.get_bonds(company)):
					if i < bond_number:
						ss = CompanyBondSale(
							price = price,
							status = FOR_SALE,
							bond_id = s.id,
							seller_id = current_user.id,
						)
						db.session.add(ss)
						db.session.commit()
			else:
				flash('You canot sell bonds you don\'t have', 'error')
		except ValueError:
			flash('value error', 'error')
	return render_template('market/company_bond_sell.html', title='Company bond market', company=company, user_bond_number=current_user.bond_number(company))




@market.route('/assets/l/stocks/<int:company_id>', methods = ['GET', 'POST'])
@login_required
def stock_market(company_id):
	company = Company.query.get_or_404(company_id)
	# share_sales = db.session.query(CompanyShareSale).where(CompanyShareSale.status == FOR_SALE).all()
	share_sales = db.session.query(
			func.count(CompanyShareSale.price).label('share_number'),
			CompanyShareSale,
			CompanyShare,
			Company,
			User,
		)\
		.join(CompanyShare, CompanyShareSale.share_id == CompanyShare.id)\
		.join(Company, CompanyShare.company_id == Company.id)\
		.join(User, CompanyShare.owner_id == User.id)\
		.where(Company.id == company_id, CompanyShareSale.status == FOR_SALE)\
		.group_by(User.id, CompanyShareSale.price)\
		.order_by(desc('share_number'))
	return render_template('market/company_stock_market.html', title='Company stock market', company=company, share_sales=share_sales.all())



@market.route('/assets/l/bonds/<int:company_id>', methods = ['GET', 'POST'])
@login_required
def bond_market(company_id):
	company = Company.query.get_or_404(company_id)
	bond_sales = db.session.query(
		func.count(CompanyBondSale.price).label('number'),
		CompanyBondSale,
		CompanyBond,
		User,
	)\
	.join(CompanyBond, CompanyBondSale.bond_id == CompanyBond.id)\
	.join(User, CompanyBond.owner_id == User.id)\
	.where(CompanyBond.company_id == 6, CompanyBondSale.status == FOR_SALE)\
	.group_by(CompanyBond.owner_id, CompanyBond.value, CompanyBond.interest_rate, CompanyBondSale.price)\
	.order_by(CompanyBond.owner_id, CompanyBond.value, CompanyBond.interest_rate, CompanyBondSale.price)
	return render_template('market/company_bond_market.html', title='Company bond market', company=company, bond_sales=bond_sales.all())

market_site/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from market_site import bc, db
from market_site.users.forms import LoginForm, TransactionForm
from market_site.models import User
from market_site.config import PHYSICAL_PERSON, TRANSACTIO_ERROR
from flask_login import login_user, logout_user, login_required, current_user
from datetime import datetime

users = Blueprint("users", __name__, template_folder="templates")

@users.route('/login', methods=['GET', 'POST'])
def login():
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(username=form.username.data).first()
		if not user:
			flash('user not found!!!', 'error')
			return redirect(url_for('users.login'))

		if bc.check_password_hash(user.password, form.password.data):
			user.last_login = datetime.now()
			db.session.commit()

			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			if next_page:
				return redirect(next_page)
			else:
				# return redirect(url_for('home.home'))
				return redirect('/home')
		else:
			flash('Login unsucessfull!', 'error')

	return render_template('login.html', title='', form=form)

@users.route('/make_transaction', methods=['GET', 'POST'])
@login_required
def make_transaction():
	form = TransactionForm()
	receipient_id = request.args.get('receipient_id', None, type=int)
	amount = request.args.get('amount', None, type=float)

	if receipient_id:
		form.receipient_id.data = receipient_id
	if amount:
		form.amount.data = amount

	if form.validate_on_submit():
		user = User.query.get(form.receipient_id.data)
		if not user or receipient_id == current_user.id:
			flash('user not found!!!', 'error')
			redirect(url_for('users.make_transaction'))

		if not (form.amount.data > 0 and form.amount.data <= current_user.balance):
			flash('amount error amount must > 0 and smaller than your balance', 'error')
			redirect(url_for('users.make_transaction'))
		result = current_user.pay(float(form.amount.data), user, info=form.info.data)
		if result == TRANSACTIO_ERROR:
			flash(result, 'error')
		else:
			flash(result, 'success')
	return render_template('transaction/make_transaction.html', title='Make Transaction', form=form)


@users.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('users.login'))


@users.route('/users', methods=['POST', 'GET'])
@login_required
def user_list():
	page = request.args.get('page', 1, type=int)
	# users = User.query.filter_by(type=PHYSICAL_PERSON)\
	# 		.paginate(page=page, per_page=15)
	users = User.query.paginate(page=page, per_page=15)
	return render_template('user/users.html', title='Users', users=users)

@users.route('/user/<int:user_id>', methods=['POST', 'GET'])
@login_required
def user(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('user/user.html', title='User ' + user.username, user=user)




@users.route('/user/<int:user_id>/h')
@login_required
def user_hard_assets(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('user/hard_assets.html', title='Hard assets', user=user)

@users.route('/user/<int:user_id>/l')
@login_required
def user_liquid_assets(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('user/liquid_assets.html', title='Liquid assets', user=user)

@users.route('/user/<int:user_id>/l/shares')
@login_required
def user_shares(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('user/shares.html', title='Shares', user=user)

@users.route('/user/<int:user_id>/l/bonds')
@login_required
def user_bonds(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('user/bonds.html', title='Bonds', user=user)



@users.route('/user/<int:user_id>/auctions')
@login_required
def user_auctions(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('user/auctions.html', title='Auctions', user=user)

@users.route('/user/<int:user_id>/sales')
@login_required
def user_sales(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('user/sales.html', title='Sales sales', user=user)

@users.route('/user/<int:user_id>/sales/asset/h')
@login_required
def user_hsales(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('user/hard_assets_sales.html', title='Sales hard sales', user=user)

@users.route('/user/<int:user_id>/sales/asset/l')
@login_required
def user_lsales(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('user/liquid_assets_sales.html', title='Sales liquid sales', user=user)



@users.route('/user/<int:user_id>/loans')
@login_required
def user_loans(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('user/loans.html', title='Loans', user=user)

@users.route('/user/<int:user_id>/loans/bank')
@login_required
def user_bank_loans(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('user/bank_loans.html', title='Bank loans', user=user)

@users.route('/user/<int:user_id>/loans/personal')
@login_required
def user_personal_loans(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('user/personal_loans.html', title='Personal loans', user=user)



@users.route('/user/<int:user_id>/transactions')
@login_required
def user_transactions(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('user/transactions.html', title='Transactions', user=user)

@users.route('/user/<int:user_id>/transactions/made')
@login_required
def user_transactions_made(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('user/transactions_made.html', title='Transactions made', user=user)

@users.route('/user/<int:user_id>/transactions/received')
@login_required
def user_transactions_received(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('user/transactions_received.html', title='Transactions received', user=user)

market_site/templates/borrow.html
{% extends "layout.html" %}
{% block style %}
<style>
    img[bank_logo_min] {
        display: inline-block;
        max-height: 2em;
    }
</style>
{% endblock %}
{% block content %}
<table tb>
    <tr>
        <th>Bank logo</th>
        <th>Bank Name</th>
        <th>Bank value</th>
        <th>Debt</th>
    </tr>
    {% for bank in banks %}
    <tr>
        <td>
            <img bank_logo_min src="/static/logos/{{ bank.get_images()[0] }}" alt="{{ bank.name }} image">
        </td>
        <td>{{ bank.name }}</td>
        <td>${{ "{:,.2f}".format(bank.legal_person.balance) }}</td>
        <td></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

market_site/templates/index.html
{% extends "layout.html" %}
{% block content %}

My auctions: <a href="/auctions/user/{{ current_user.id }}">auctions</a><br>
My sales: <a href="/sales/user/{{ current_user.id }}">sales</a><br>

<br>
<h3>Payments made</h3>
Total payments made: <span class="m">{{ '{:,.2f}'.format(current_user.total_payments_made) }}</span>
<table tb>
    <tr>
        <th>Amount</th>
        <th>Receipient</th>
        <th>Time</th>
        <th>Info</th>
    </tr>
    {% for payment in current_user.payments_made()[-10:] %}
        <tr>
            <td><span class="m">{{ payment.amount }}</span></td>
            <td>{{ payment.payee.username }}</td>
            <td><span class="t">{{ payment.time.strftime('%d/%m/%Y %H:%M:%S') }}</span> </td>
            <td>{{ payment.info }}</td>
        </tr>
    {% endfor %}
</table>
<br>

<h3>Payments received</h3>
Total payments received: <span class="m">{{ '{:,.2f}'.format(current_user.total_payments_received) }}</span>
<table tb>
    <tr>
        <th>Amount</th>
        <th>Payer</th>
        <th>Time</th>
        <th>Info</th>
    </tr>
    {% for payment in current_user.payments_received()[-10:] %}
        <tr>
            <td><span class="m">{{ payment.amount }}</span></td>
            <td>{{ payment.payer.username }}</td>
            <td><span class="t">{{ payment.time.strftime('%d/%m/%Y %H:%M:%S') }}</span> </td>
            <td>{{ payment.info }}</td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

market_site/templates/layout.html
{% from "macros.html" import
	link, btn_link, status, tf_status, multi_status, ha_sale_status,
	sale_status, user_link, ha_link, ha_image, company_link, company_image,
	ha_compact, pagination_, pagination, auction_link, auction_image, auction_market,
	ha_market,
with context %}
{% from "bootstrap4/pagination.html" import render_pagination %}
{% from 'bootstrap4/utils.html' import render_messages %}
{% from 'bootstrap4/utils.html' import render_icon %}
{% from 'bootstrap4/nav.html' import render_breadcrumb_item %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        Market site
        {% if title %}
         - {{title}}
        {% endif %}
    </title>

    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script> -->

	<link rel="stylesheet" href="{{url_for('static', filename='jquery/jquery-ui.min.css')}}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{{url_for('static', filename='css/modal.css')}}">
	<link rel="stylesheet" href="{{url_for('static', filename='css/alert.css')}}">
	<link rel="stylesheet" href="{{url_for('static', filename='css/btn.css')}}">
	<!-- <link rel="stylesheet" href="{{url_for('static', filename='css/input.css')}}"> -->
	<link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
	<link rel="icon" href="{{ url_for('static', filename='logos/logo1.1.png') }}">

	{% block styles %}
		<!-- Bootstrap CSS -->
		{{ bootstrap.load_css() }}
	{% endblock %}

    {% block style %}{% endblock %}
    {% block meta_tags %}{% endblock %}
</head>

<body>
	<header>
		<img src="{{ url_for('static', filename='logos/logo1.1.png') }}" logo>
		<img src="{{ url_for('static', filename='logos/logo1.2.png') }}" logo>
	</header>

	<div main>
		{% if current_user.is_authenticated and request.route != "/login" %}
			<div class="sidenav">
				<div>
					<a href="/home">
						<img user_image src="{{ url_for('static', filename='logos/profile.png') }}" alt="">
					</a>
					<br>
					<b>
						<!-- LEGAL_PERSON == 0 -->
						{% if current_user.type == 0 %}
							CEO of
							<br>
							{{ current_user.get_company().name }}
						{% else %}
							{{current_user.username}}
						{% endif %}
					</b>
				</div>
				{{ link(url_for('home.user_home'), 'Home') }}<br>
				{{ link(url_for('users.user_list'), 'Users') }}<br>
				{{ link(url_for('market.market_'), 'Market') }}<br>
				{{ link(url_for('users.make_transaction'), 'Transaction') }}<br>
				{{ link(url_for('users.logout'), 'Logout') }}<br>
			</div>
			<!-- <div class="sidenav">
				<div>
					<a href="/home">
						<img user_image src="{{ url_for('static', filename='logos/profile.png') }}" alt="">
					</a>
					<br>
					<b>
						{% if current_user.type == 0 %}
							CEO of
							<br>
							{{ current_user.get_company().name }}
						{% else %}
							{{current_user.username}}
						{% endif %}
					</b>
				</div>
				<div class="container">
					<ul class="nav flex-column">
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('home.user_home') }}">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('users.user_list') }}">Users</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('market.market_') }}">Market</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('users.make_transaction') }}">Transaction</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
						</li>
					</ul>
				</div>
			</div> -->
		{% endif %}
		<div content>
			<div class="title">
				{% if title %}
					{{title}}
				{% endif %}
			</div>

			{% if current_user.is_authenticated %}
				<b>Your balance:</b> {{ current_user.balance | price }}
				<br>
				<br>
			{% endif %}

			{{ render_messages(dismissible=true, dismiss_animate=true, default_category='info') }}

			{% if breadcrumbs  %}
			
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb breadcrumb-sm">
					{% for breadcrumb in breadcrumbs %}
						{% if loop.last %}
							<li class="breadcrumb-item active" aria-current="page">{{ breadcrumb.text }}</li>
						{% else %}
							<li class="breadcrumb-item"><a href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a></li>
						{% endif %}
					{% endfor %}
				</ol>
			</nav>
			{% endif %}
			<br>

			{% block content %}
			{% endblock %}
		</div>
	</div>

	<footer>
		Copyright &copy; 2021 Market site inc., All rights reserved.
		<br>
		<a href="#">Terms of Service</a> | <a href="#">Privacy Policy</a>
	</footer>

{% block scripts %}
	<!-- Optional JavaScript -->
	{{ bootstrap.load_js() }}
	<script src="{{url_for('static', filename='js/script.js')}}"></script>
	<script src="{{url_for('static', filename='js/modal_script.js')}}"></script>
	<!-- <script src="{{url_for('static', filename='jquery/external/jquery/jquery.js')}}"></script>
	<script src="{{url_for('static', filename='jquery/jquery-ui.min.js')}}"></script> -->
{% endblock %}


{% block javascript %}{% endblock %}
</body>

market_site/templates/login.html
{% extends "layout.html" %}
{% block style %}
<style>
    .form {
        width: clamp(150px, 30%, 450px);
    }
</style>
{% endblock %}
{% block content %}
<form action="" method="POST" class="form">
    {{ form.hidden_tag() }}
    <fieldset>
        <legend>Sign in</legend>
        <div>
            <table>
                <tr>
                    <td>{{ form.username.label() }}</td>
                    <td>
                        {{ form.username() }}
                        {% if form.username.errors %}
                            <div class="invalid_feadback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>{{ form.password.label() }}</td>
                    <td>
                        {{ form.password() }}
                        {% if form.password.errors %}
                            <div class="invalid_feadback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% endif %} 
                    </td>
                </tr>
                <tr>
                    <td colspam="2">
                        {{ form.submit.label() }}
                        {{ form.submit() }}
                    </td>
                </tr>
            </table>
        </div>
    </fieldset>
</form>
<div>
    {#
    <small>
        Do you need an account? <a href="{{url_for('register')}}">Sign in</a><br>
        Forgot password? 
    </small>
    #}
</div>
{% endblock %}

market_site/templates/macros.html
{% macro link(path, name) %}
    <a href="{{ path }}">{{ name }}</a>
{% endmacro %}

{% macro btn_link(path, name) %}
    <a href="{{ path }}"><button>{{ name }}</button></a>
{% endmacro %}

{% macro status(classes='', name='') %}
<span class="status {{ classes }}">{{ name }}</span>
{% endmacro %}

{% macro tf_status(bool, options=[]) %}
	{%- if bool -%}
		{{ status(options[0]) if options.__len__() >= 1 else status('true') }}
	{% else %}
		{{ status(options[1]) if options.__len__() >= 2 else status('false') }}
	{% endif %}
{% endmacro %}

{% macro multi_status(options=[], default='', additional_classes='') %}
	{% set is_default = namespace(value = true) %}
	{%- for bool, classes in options -%}
		{%- if bool -%}
			{{ status(additional_classes + ' ' + classes) }}
			{% set is_default.value = false %}
			{% break %}
		{% endif  %}
	{% endfor %}
	{%- if is_default.value -%}
{{ status(default) }}
	{% endif %}
{% endmacro %}

{% macro ha_sale_status(asset, additional_classes='') %}
{{ multi_status(
	options = [
		(asset.is_on_sale(), 'for_sale'),
		(asset.is_on_auction(), 'auction'),
	],
	default='not_for_sale', additional_classes=additional_classes)
}}
{% endmacro %}

{% macro sale_status(sale_status) %}
    {{ tf_status(sale_status, ['sold', 'for_sale']) if sale_status }}
{% endmacro %}


{% macro user_link(user) %}
    {{ link(url_for('users.user', user_id=user.id), user.username) if user }}
{% endmacro %}

{% macro ha_link(asset) %}
	{{ link(url_for('hard_assets.hard_asset', ha_id=asset.id), asset.name) }}
{% endmacro %}

{% macro ha_image(asset, size='w3', attributes='') %}
    <div class="ha_img_container {{ size }}">
		<a href="{{ url_for('hard_assets.hard_asset', ha_id=asset.id) }}">
			<img {{ attributes | safe }} class="asset_image"
			src="/static/assets/hard/{{ asset.get_images()[0] }}" alt="{{ asset.name }} image">
		</a>
	</div>
{% endmacro %}

{% macro company_link(company) %}
    {{ link(url_for('liquid_assets.company', company_id=company.id), company.name) }}
{% endmacro %}

{% macro company_image(company, size='h1', attributes='') %}
    <a href="{{ url_for('liquid_assets.company', company_id=company.id) }}">
        <img {{ attributes | safe }} class="company_logo {{ size }}" src="/static/companies/{{ company.get_images()[0] }}" alt="{{ company.name }} image">
    </a>
{% endmacro %}

{% macro ha_compact(asset) %}
<div class="asset_item">
    <div>
        {{ ha_image(asset) }}
    </div>
    <div>
        <span class="gray">Name: </span>{{ ha_link(asset) }}</a><br>
        <span class="gray">Value: </span>{{ asset.value | price }}<br>
        <span class="gray">Type: </span><span class="small">{{ asset.type }}</span><br>
        <span class="gray">Info: </span><span class="small">{{ asset.info }}</span><br>
        <span class="gray">Status: </span>{{ ha_sale_status(asset, 'small') }}
    </div>
</div>
{% endmacro %}







































{#
{% macro pagination_(items, func, params={}) %}
    {%- if items.pages > 1 -%}
        <div class="pagination">
            {%- if items.has_prev -%}
                <a  href="{{ url_for(func, page=items.prev_num, **params) }}">&laquo;</a>
            {% endif %}
            {%- for page_num in items.iter_pages(left_edge=2, right_edge=2, left_current=2, right_current=2) -%}
                {%- if page_num -%}
                    {%- if items.page == page_num -%}
                        <a class="current" href="{{ url_for(func, page=page_num, **params) }}">{{ page_num }}</a>
                    {% else %}
                        <a href="{{ url_for(func, page=page_num, **params) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
            {%- if items.has_next -%}
                <a href="{{ url_for(func, page=items.next_num, **params) }}">&raquo;</a>
            {% endif %}
        </div>
    {% endif %}
{% endmacro %}

{% macro pagination(items, func, retain_params=False, params={}) %}
	{%- if retain_params and request.args.to_dict(flat=False) -%}
		{{ pagination_(items, func, params=merge_dicts(params, request.args.to_dict(flat=False))) }}
	{% else %}
		{{ pagination_(items, func, params) }}
	{% endif %}
{% endmacro %}
#}

{% macro auction_link(auction) %}
    {{ link(url_for('auction.auction_page', auction_id=auction.id), auction.hard_asset.name) }}
{% endmacro %}

{% macro auction_image(auction) %}
    <a href="{{ url_for('auction.auction_page', auction_id=auction.id)}} ">
        <img vertical_logo src="/static/assets/hard/{{ auction.hard_asset.get_images()[0] }}"
            alt="{{ auction.hard_asset.name }} image">
    </a>
{% endmacro %}

{% macro auction_market(auction) %}
    <div class="container">
        <div class="logo">
            {{ auction_image(auction) }}
        </div>
        <br>
        <span class="name">{{ auction_link(auction) }}</span>
        <br>
        <div info>
            <span mark>Auction price</span>: {{ auction.final_price | price }}<br>
            <span mark>Propery value</span>: {{ auction.hard_asset.value | price }}<br>
            <span mark>Current owner</span>: {{ user_link(auction.get_seller()) }}<br>
            <span mark>Auction start</span>: {{ auction.start | time }}<br>
            <span mark>Status</span>: {{ status('involved') if auction.is_bidder(current_user) else status('not_involved') }}
        </div>
    </div>
{% endmacro %}

{% macro ha_market(sale) %}
    <div class="container">
        <div class="logo">
            {{ ha_image(sale.hard_asset, attributes='vertical_logo') }}
        </div>
        <br>
        <span class="name">{{ ha_link(sale.hard_asset) }}</span>
        <br>
        <div info>
            <span mark>Sale price</span>: {{ sale.price | price }}<br>
            <span mark>Propery value</span>: {{ sale.hard_asset.value | price }}<br>
            <span mark>Current owner</span>: {{ user_link(sale.get_seller()) }}</a><br>
            <span mark>Sale start</span>: {{ sale.start | time }}<br>
        </div>
    </div>
{% endmacro %}

market_site/templates/test.html
{% extends 'layout.html' %}
{% block test %}
{% endblock test %}